services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    environment:
      APP_NAME: booking_lap
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: booking_lap
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: booking_lap
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql-data: {}
